---
title: "Econometria"
author: "João Ricardo F. de Lima"
output: 
    html_document:
        theme: flatly
        number_sections: no
        highlight: textmate
        #includes: 
        #  in_header: "header.html"
        toc: yes
        toc_float:
          collapsed: yes
          smooth_scroll: yes 
---

<br>

# ECONOMETRIA I

<br>

## 1. APRESENTAÇÃO

<br>

A disciplina de **Econometria** antigamente era chamada de Estatística Econômica. A disciplina surgiu da evolução dos métodos de estimação e das formas de análise e acabou contribuindo para o desenvolvimento de outros ramos da estatística. 

Em linhas gerais, a  **Econometria** é considerada a junção de três disciplinas: economia, matemática e estatística. Assim, a  **Econometria** é uma disciplina baseada no desenvolvimento de métodos estatísticos para estimar relações econômicas. 

Para tal, é necessário que se tenha uma amostra de dados que permita encontrar estimadores/estimativas sobre as relações econômicas dessa população. O mais comum é que obtenhamos amostras de dados econômicos. 

A  **Econometria** é considerada uma importante ferramenta da Economia, que pode ser usada para encontrar relações de causalidade entre variáveis. Dentre um grande universo de opções de usos da ferramenta, pode-se destacar:

* Avaliar o impacto de políticas públicas; 
* Avaliar o efeito de programas implementados em empresas; 
* Testar relações teóricas da Economia;
* Fazer previsões de variáveis econômicas;

O curso de **Econometria I** cobre o programa básico de **Econometria** em nível iniciante com ênfase na parte aplicada. 

<br>

## 2. OBJETIVOS

<br>

Propiciar ao estudante conhecimentos que possibilitem um tratamento formal dos processos de investigação empírica, com base em processos operacionais e modelagem econométrica, fundamentais ao profissional de economia para exercício de sua profissão. 

Especificamente pretende-se:

1. Desenvolver a teoria econométrica elementar, de forma a possibilitar ao estudante um melhor entendimento dos métodos empregados;

2. Examinar algumas técnicas econométricas importantes, com ênfase no entendimento e na aplicação destas;
 
3. Desenvolver a habilidade dos estudantes em avaliar modelos econômicos com respeito aos aspectos estatísticos e econômicos;

4. Treinar o estudante na aplicação de métodos econométricos, mediante a realização de um estudo introdutório que envolva a formulação do modelo, coleta de dados, estimação e interpretação dos resultados.

<br>

## 3. AVALIAÇÃO

<br>

A avaliação do curso constará de provas e exercícios. As Provas cobrirão a matéria nova ministrada até a aula anterior à data da prova e deverão ser resolvidas na sala de aula sem consulta. Os Exercícios constituir-se-ão de problemas demonstrativos, com a finalidade de esclarecer e fixar bem os conceitos desenvolvidos na sala de aula. No curso será utilizado o software estatístico R. 

<br>

## 4. BIBLIOGRAFIA

<br>

WOOLDRIDGE, J. *Introdução à Econometria: uma abordagem moderna*. 4.ed. São Paulo: Cengage Learning, 2017. 878p. 

<br>

**Outros Textos**: 

<br>

GUJARATI, D. N.; PORTER D.C. *Basic Econometrics*. 5th ed. NY: McGraw Hill, 2009. 922p. 

GUJARATI, D.N.. *Econometrics by example*. NY: Palgrave Macmillan, 2011. 371p.

GUJARATI, Damodar N. *Econometria Básica*. Quarta Edição. Rio de Janeiro: Elsevier, 2006. 812p. 

HILL, Carter, GRIFFITHS, W. e JUDGE, G. *Econometria*. 3.ed. São Paulo, Editora Saraiva, 2010. 471p. 

MADDALA, G. S. *Introdução à Econometria*. Rio de Janeiro: LTC Editora, 2003. 345p. 

STOCK, J.H.; WATSON, M. W. *Econometria*. São Paulo: Addison Wesley, 2004. 485p. 

VASCONCELOS, M. A. S. e ALVES, D. (Editores) *Manual de Econometria*. São Paulo: Editora Atlas, 2000. 308p. 

<br>

## 5. TÓPICOS DO CURSO

<br>
<br>

#### **INTRODUÇÃO** 

<br>

1.1 Definição e Objetivos da Econometria 

1.2 Metodologia da Econometria

1.3 Tipos e Características dos Dados Econômicos

<br>
                
#### **MODELO DE REGRESSÃO LINEAR SIMPLES**

<br>

2.1 Definição do Modelo de Regressão Simples 

2.2 Derivação das estimativas de Mínimos Quadrados Ordinários (MQO) 

2.3 Características de MQO em determinada amostra de Dados 

2.4 Unidades de Medida e Forma Funcional 

2.5 Valores esperados e Variâncias dos estimadores de MQO. 

<br>
              
              
#### **MODELO DE REGRESSÃO LINEAR MÚLTIPLA** 

<br>

3.1 Funcionalidade da Regressão Múltipla  

3.2 Mecânica e Interpretação dos MQO 	

3.3 O Valor Esperado dos Estimadores de MQO 

3.4 A variância dos Estimadores de MQO

3.5 A Eficiência de MQO: O teorema de Gauss-Markov 

<br>

#### **ANÁLISE DE REGRESSÃO MÚLTIPLA: INFERÊNCIA** 

<br>

4.1 Distribuições amostrais dos estimadores de MQO  

4.2 Testes de Hipóteses sobre um único parâmetro populacional: o teste "t" 

4.3 Intervalos de Confiança 

4.4 Testes de Hipóteses sobre uma combinação linear dos parâmetros

4.5 Testes de restrições lineares múltiplas: o teste "F" 

<br>

#### **ANÁLISE DE REGRESSÃO MÚLTIPLA COM VARIÁVEIS QUALITATIVAS (DUMMY)** 

<br>

5.1 Uma única variável dummy independente  

5.2 O uso de variáveis dummy para categorias múltiplas 

5.3 Interações envolvendo variáveis dummy 

<br>

#### **PROBLEMAS ECONOMÉTRICOS NO MODELO LINEAR** 

<br>

6.1. Multicolinearidade 

6.2. Heterocedasticidade 

6.3. Autocorrelação 

6.4. Especificação do Modelo 

<br>
         
#### **MODELOS COM VARIÁVEIS DEPENDENTES LIMITADAS E CORREÇÕES DE SELEÇÃO AMOSTRAL** 

<br>

7.1 Variável Dependente Binária (Modelos Logit e Probit) 

<br>

#### **MODELOS COM DADOS EM PAINEL** 

<br>

8.1 MODELO COM EFEITOS FIXOS

8.2 MODELO COM EFEITOS ALEATÓRIOS 

<br>

# [AULA 1](https://jricardofl.github.io/econometria1/econ1_aula1)

# AULA 2

# AULA 3

# AULA 4

# AULA 5

# AULA 6

# AULA 7

# AULA 8

# AULA 9

# AULA 10

